[package]
name = "todo_rs_tui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.27.0"
ratatui = "0.26.0"
rusqlite = "0.30.0"
simple-home-dir = "0.3.2"
